# Generated by Django 4.1.7 on 2023-07-16 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='master_courses',
            table=None,
        ),
    ]
