# Generated by Django 4.1.7 on 2023-07-16 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_list', '0003_alter_master_courses_course_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='master_courses',
            table='course_master_data',
        ),
    ]
