# Generated by Django 4.1.7 on 2023-07-16 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_list', '0004_alter_master_courses_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='master_courses',
            table='master_courses_table',
        ),
    ]
